// <auto-generated />
using System;
using Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322065617_TtsVoiceProfile")]
    partial class TtsVoiceProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Domain.Entities.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Businesses", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.BusinessOwnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BusinessOwnerProfiles", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.EmployeeProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Department")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Position")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EmployeeProfiles", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d2c6e75-5f4d-4c7f-97db-1c28a56d8b01"),
                            Code = "en-US",
                            IsActive = true,
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("38f7c5e6-5d6b-4ac3-8d7d-4bfccecc2fb3"),
                            Code = "vi-VN",
                            IsActive = true,
                            Name = "Vietnamese"
                        },
                        new
                        {
                            Id = new Guid("a3f2cc5c-4631-4f3c-80c2-5b4c81d7b1e1"),
                            Code = "ja-JP",
                            IsActive = true,
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = new Guid("b1a3f6c2-6c20-4a7a-9a01-7c8f6a9b7d10"),
                            Code = "zh-CN",
                            IsActive = true,
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = new Guid("c2b4e7d3-7d31-4b8b-8b12-8d9a7b0c8e21"),
                            Code = "fr-FR",
                            IsActive = true,
                            Name = "French"
                        },
                        new
                        {
                            Id = new Guid("d3c5f8e4-8e42-4c9c-9c23-9eab8c1d9f32"),
                            Code = "ru-RU",
                            IsActive = true,
                            Name = "Russian"
                        },
                        new
                        {
                            Id = new Guid("e4d609f5-9f53-4dad-ad34-afbc9d2e0a43"),
                            Code = "de-DE",
                            IsActive = true,
                            Name = "German"
                        },
                        new
                        {
                            Id = new Guid("f5e71a06-a064-4ebe-be45-b0cd0e3f1b54"),
                            Code = "ko-KR",
                            IsActive = true,
                            Name = "Korean"
                        },
                        new
                        {
                            Id = new Guid("06f82b17-b175-4fcf-cf56-c1de1f402c65"),
                            Code = "es-ES",
                            IsActive = true,
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = new Guid("17a93c28-c286-40d0-d067-d2ef20513d76"),
                            Code = "it-IT",
                            IsActive = true,
                            Name = "Italian"
                        },
                        new
                        {
                            Id = new Guid("28ba4d39-d397-41e1-e178-e3f031624e87"),
                            Code = "th-TH",
                            IsActive = true,
                            Name = "Thai"
                        },
                        new
                        {
                            Id = new Guid("39cb5e4a-e4a8-42f2-f289-f40142735f98"),
                            Code = "id-ID",
                            IsActive = true,
                            Name = "Indonesian"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.NarrationAudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("BlobId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsTts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("NarrationContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("TtsVoiceProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Voice")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TtsVoiceProfileId");

                    b.HasIndex("NarrationContentId", "TtsVoiceProfileId")
                        .IsUnique()
                        .HasFilter("[TtsVoiceProfileId] IS NOT NULL");

                    b.ToTable("NarrationAudios", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "RevokedAtUtc");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConcurrencyStamp = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ConcurrencyStamp = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
                            Name = "BusinessOwner",
                            NormalizedName = "BUSINESSOWNER"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ConcurrencyStamp = "cccccccc-cccc-cccc-cccc-cccccccccccc",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.Stall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Stalls", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.StallGeoFence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int?>("MaxZoom")
                        .HasColumnType("int");

                    b.Property<int?>("MinZoom")
                        .HasColumnType("int");

                    b.Property<string>("PolygonJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StallId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StallId");

                    b.ToTable("StallGeoFences", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.StallLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("MapProviderPlaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("RadiusMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("StallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("StallId");

                    b.ToTable("StallLocations", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.StallMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Caption")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("StallId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StallId");

                    b.ToTable("StallMedia", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.StallNarrationContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScriptText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("StallId");

                    b.ToTable("StallNarrationContents", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.TtsVoiceProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Style")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VoiceName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("TtsVoiceProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Giọng nam, trung tính",
                            DisplayName = "Nam Minh",
                            IsActive = true,
                            IsDefault = true,
                            LanguageId = new Guid("38f7c5e6-5d6b-4ac3-8d7d-4bfccecc2fb3"),
                            Priority = 0,
                            Provider = "AzureTts",
                            VoiceName = "vi-VN-NamMinhNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Giọng nữ, rõ ràng",
                            DisplayName = "Hoài My",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("38f7c5e6-5d6b-4ac3-8d7d-4bfccecc2fb3"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "vi-VN-HoaiMyNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-3333-2222-2222-222222222222"),
                            Description = "Giọng nữ, thân thiện",
                            DisplayName = "Ava",
                            IsActive = true,
                            IsDefault = true,
                            LanguageId = new Guid("0d2c6e75-5f4d-4c7f-97db-1c28a56d8b01"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "en-US-AvaMultilingualNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-1234-2222-2222-222222222222"),
                            Description = "Giọng nam, trung tính",
                            DisplayName = "Andrew",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("0d2c6e75-5f4d-4c7f-97db-1c28a56d8b01"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "en-US-AndrewMultilingualNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0001-2222-2222-222222222222"),
                            Description = "Giọng nữ, rõ ràng",
                            DisplayName = "Amanda",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("0d2c6e75-5f4d-4c7f-97db-1c28a56d8b01"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "en-US-AmandaMultilingualNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-2222-2222-222222222222"),
                            Description = "Giọng nam, ấm áp",
                            DisplayName = "Adam",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("0d2c6e75-5f4d-4c7f-97db-1c28a56d8b01"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "en-US-AdamMultilingualNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0003-2222-2222-222222222222"),
                            Description = "Giọng nữ, vui vẻ",
                            DisplayName = "Emma",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("0d2c6e75-5f4d-4c7f-97db-1c28a56d8b01"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "en-US-EmmaMultilingualNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0004-2222-2222-222222222222"),
                            Description = "Giọng nữ, trẻ trung",
                            DisplayName = "Phoebe",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("0d2c6e75-5f4d-4c7f-97db-1c28a56d8b01"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "en-US-PhoebeMultilingualNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0005-2222-2222-222222222222"),
                            Description = "Giọng nữ, vui vẻ",
                            DisplayName = "Nanami",
                            IsActive = true,
                            IsDefault = true,
                            LanguageId = new Guid("a3f2cc5c-4631-4f3c-80c2-5b4c81d7b1e1"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "ja-JP-NanamiNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0006-2222-2222-222222222222"),
                            Description = "Giọng nam, trung tính",
                            DisplayName = "Keita",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("a3f2cc5c-4631-4f3c-80c2-5b4c81d7b1e1"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "ja-JP-KeitaNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0007-2222-2222-222222222222"),
                            Description = "Giọng nữ, thân thiện",
                            DisplayName = "Xiaochen",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("b1a3f6c2-6c20-4a7a-9a01-7c8f6a9b7d10"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "zh-CN-XiaochenMultilingualNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0008-2222-2222-222222222222"),
                            Description = "Giọng nam, vui vẻ",
                            DisplayName = "Yunxi",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("b1a3f6c2-6c20-4a7a-9a01-7c8f6a9b7d10"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "zh-CN-YunxiNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0009-2222-2222-222222222222"),
                            Description = "Giọng nữ, ám áp",
                            DisplayName = "Xiaoxiao",
                            IsActive = true,
                            IsDefault = true,
                            LanguageId = new Guid("b1a3f6c2-6c20-4a7a-9a01-7c8f6a9b7d10"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "zh-CN-XiaoxiaoNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0010-2222-2222-222222222222"),
                            Description = "Giọng nam, trung tính",
                            DisplayName = "Yunjian",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("b1a3f6c2-6c20-4a7a-9a01-7c8f6a9b7d10"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "zh-CN-YunjianNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0011-2222-2222-222222222222"),
                            Description = "Giọng nữ, trung tính",
                            DisplayName = "Denise",
                            IsActive = true,
                            IsDefault = true,
                            LanguageId = new Guid("c2b4e7d3-7d31-4b8b-8b12-8d9a7b0c8e21"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "fr-FR-DeniseNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0012-2222-2222-222222222222"),
                            Description = "Giọng nam, mạnh mẽ",
                            DisplayName = "Henri",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("c2b4e7d3-7d31-4b8b-8b12-8d9a7b0c8e21"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "fr-FR-HenriNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0013-2222-2222-222222222222"),
                            Description = "Giọng nữ, trung tính",
                            DisplayName = "Svetlana",
                            IsActive = true,
                            IsDefault = true,
                            LanguageId = new Guid("d3c5f8e4-8e42-4c9c-9c23-9eab8c1d9f32"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "ru-RU-SvetlanaNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0014-2222-2222-222222222222"),
                            Description = "Giọng nam, trung tính",
                            DisplayName = "Dmitry",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("d3c5f8e4-8e42-4c9c-9c23-9eab8c1d9f32"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "ru-RU-DmitryNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0015-2222-2222-222222222222"),
                            Description = "Giọng nữ, trung tính",
                            DisplayName = "Katja",
                            IsActive = true,
                            IsDefault = true,
                            LanguageId = new Guid("e4d609f5-9f53-4dad-ad34-afbc9d2e0a43"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "de-DE-KatjaNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0016-2222-2222-222222222222"),
                            Description = "Giọng nam, trung tính",
                            DisplayName = "Conrad",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("e4d609f5-9f53-4dad-ad34-afbc9d2e0a43"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "de-DE-ConradNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0017-2222-2222-222222222222"),
                            Description = "Giọng nữ, trung tính",
                            DisplayName = "Sun-Hi",
                            IsActive = true,
                            IsDefault = true,
                            LanguageId = new Guid("f5e71a06-a064-4ebe-be45-b0cd0e3f1b54"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "ko-KR-SunHiNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0018-2222-2222-222222222222"),
                            Description = "Giọng nam, trung tính",
                            DisplayName = "InJoon",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("f5e71a06-a064-4ebe-be45-b0cd0e3f1b54"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "ko-KR-InJoonNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0019-2222-2222-222222222222"),
                            Description = "Giọng nữ, trung tính",
                            DisplayName = "Elvira",
                            IsActive = true,
                            IsDefault = true,
                            LanguageId = new Guid("06f82b17-b175-4fcf-cf56-c1de1f402c65"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "es-ES-ElviraNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0020-2222-2222-222222222222"),
                            Description = "Giọng nam, trung tính",
                            DisplayName = "Alvaro",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("06f82b17-b175-4fcf-cf56-c1de1f402c65"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "es-ES-AlvaroNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0021-2222-2222-222222222222"),
                            Description = "Giọng nữ, trung tính",
                            DisplayName = "Elsa",
                            IsActive = true,
                            IsDefault = true,
                            LanguageId = new Guid("17a93c28-c286-40d0-d067-d2ef20513d76"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "it-IT-ElsaNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0022-2222-2222-222222222222"),
                            Description = "Giọng nam, trung tính",
                            DisplayName = "Diego",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("17a93c28-c286-40d0-d067-d2ef20513d76"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "it-IT-DiegoNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0023-2222-2222-222222222222"),
                            Description = "Giọng nữ, trung tính",
                            DisplayName = "Premwadee",
                            IsActive = true,
                            IsDefault = true,
                            LanguageId = new Guid("28ba4d39-d397-41e1-e178-e3f031624e87"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "th-TH-PremwadeeNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0024-2222-2222-222222222222"),
                            Description = "Giọng nam, trung tính",
                            DisplayName = "Niwat",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("28ba4d39-d397-41e1-e178-e3f031624e87"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "th-TH-NiwatNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0025-2222-2222-222222222222"),
                            Description = "Giọng nữ, trung tính",
                            DisplayName = "Gadis",
                            IsActive = true,
                            IsDefault = true,
                            LanguageId = new Guid("39cb5e4a-e4a8-42f2-f289-f40142735f98"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "id-ID-GadisNeural"
                        },
                        new
                        {
                            Id = new Guid("22222222-0026-2222-2222-222222222222"),
                            Description = "Giọng nam, trung tính",
                            DisplayName = "Ardi",
                            IsActive = true,
                            IsDefault = false,
                            LanguageId = new Guid("39cb5e4a-e4a8-42f2-f289-f40142735f98"),
                            Priority = 1,
                            Provider = "AzureTts",
                            VoiceName = "id-ID-ArdiNeural"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Sex")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.VisitorLocationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal?>("AccuracyMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CapturedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VisitorLocationLogs", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.VisitorPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("AutoPlay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SpeechRate")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Voice")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("VisitorPreferences", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.VisitorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("VisitorProfiles", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.Business", b =>
                {
                    b.HasOne("Api.Domain.Entities.User", "OwnerUser")
                        .WithMany("Businesses")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Api.Domain.Entities.BusinessOwnerProfile", b =>
                {
                    b.HasOne("Api.Domain.Entities.User", "User")
                        .WithOne("BusinessOwnerProfile")
                        .HasForeignKey("Api.Domain.Entities.BusinessOwnerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Entities.EmployeeProfile", b =>
                {
                    b.HasOne("Api.Domain.Entities.User", "User")
                        .WithOne("EmployeeProfile")
                        .HasForeignKey("Api.Domain.Entities.EmployeeProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Entities.NarrationAudio", b =>
                {
                    b.HasOne("Api.Domain.Entities.StallNarrationContent", "NarrationContent")
                        .WithMany("NarrationAudios")
                        .HasForeignKey("NarrationContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.TtsVoiceProfile", "TtsVoiceProfile")
                        .WithMany("NarrationAudios")
                        .HasForeignKey("TtsVoiceProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NarrationContent");

                    b.Navigation("TtsVoiceProfile");
                });

            modelBuilder.Entity("Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Api.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Entities.Stall", b =>
                {
                    b.HasOne("Api.Domain.Entities.Business", "Business")
                        .WithMany("Stalls")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Api.Domain.Entities.StallGeoFence", b =>
                {
                    b.HasOne("Api.Domain.Entities.Stall", "Stall")
                        .WithMany("StallGeoFences")
                        .HasForeignKey("StallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stall");
                });

            modelBuilder.Entity("Api.Domain.Entities.StallLocation", b =>
                {
                    b.HasOne("Api.Domain.Entities.Stall", "Stall")
                        .WithMany("StallLocations")
                        .HasForeignKey("StallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stall");
                });

            modelBuilder.Entity("Api.Domain.Entities.StallMedia", b =>
                {
                    b.HasOne("Api.Domain.Entities.Stall", "Stall")
                        .WithMany("StallMedia")
                        .HasForeignKey("StallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stall");
                });

            modelBuilder.Entity("Api.Domain.Entities.StallNarrationContent", b =>
                {
                    b.HasOne("Api.Domain.Entities.Language", "Language")
                        .WithMany("StallNarrationContents")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.Stall", "Stall")
                        .WithMany("StallNarrationContents")
                        .HasForeignKey("StallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Stall");
                });

            modelBuilder.Entity("Api.Domain.Entities.TtsVoiceProfile", b =>
                {
                    b.HasOne("Api.Domain.Entities.Language", "Language")
                        .WithMany("TtsVoiceProfiles")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Api.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Api.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Entities.VisitorLocationLog", b =>
                {
                    b.HasOne("Api.Domain.Entities.User", "User")
                        .WithMany("VisitorLocationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Entities.VisitorPreference", b =>
                {
                    b.HasOne("Api.Domain.Entities.Language", "Language")
                        .WithMany("VisitorPreferences")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.User", "User")
                        .WithOne("VisitorPreference")
                        .HasForeignKey("Api.Domain.Entities.VisitorPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Entities.VisitorProfile", b =>
                {
                    b.HasOne("Api.Domain.Entities.Language", "Language")
                        .WithMany("VisitorProfiles")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.User", "User")
                        .WithOne("VisitorProfile")
                        .HasForeignKey("Api.Domain.Entities.VisitorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Domain.Entities.Business", b =>
                {
                    b.Navigation("Stalls");
                });

            modelBuilder.Entity("Api.Domain.Entities.Language", b =>
                {
                    b.Navigation("StallNarrationContents");

                    b.Navigation("TtsVoiceProfiles");

                    b.Navigation("VisitorPreferences");

                    b.Navigation("VisitorProfiles");
                });

            modelBuilder.Entity("Api.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Api.Domain.Entities.Stall", b =>
                {
                    b.Navigation("StallGeoFences");

                    b.Navigation("StallLocations");

                    b.Navigation("StallMedia");

                    b.Navigation("StallNarrationContents");
                });

            modelBuilder.Entity("Api.Domain.Entities.StallNarrationContent", b =>
                {
                    b.Navigation("NarrationAudios");
                });

            modelBuilder.Entity("Api.Domain.Entities.TtsVoiceProfile", b =>
                {
                    b.Navigation("NarrationAudios");
                });

            modelBuilder.Entity("Api.Domain.Entities.User", b =>
                {
                    b.Navigation("BusinessOwnerProfile");

                    b.Navigation("Businesses");

                    b.Navigation("EmployeeProfile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");

                    b.Navigation("VisitorLocationLogs");

                    b.Navigation("VisitorPreference");

                    b.Navigation("VisitorProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
